### ISSUE TITLE
Removes a revenue path for osu developers

### ISSUE THREAD

**Issue by nate-moo** [ArjixWasTaken/osu-directer#1]
This isn't good for the developers because it provides a way for people to bypass paying for osu!!!

please take down this repo!

**Comment by ArjixWasTaken** [comment]
lmao nut, immediately trying to take down my repo, lol

**Comment by ArjixWasTaken** [comment]
seriously tho, osu!supporter is supposed to be for supporting osu, not for getting osu!direct, osu!direct is a side effect of having osu!supporter

**Comment by nate-moo** [comment]
Shut your face

**Comment by ArjixWasTaken** [comment]
:wheeze:
