### ISSUE TITLE
Quick access for beatmap bug

### ISSUE THREAD

**Issue by chaniibak** [ArjixWasTaken/osu-directer#7]
hi pressing quick access for beatmap downloads the map instead of taking me to the maps page like how i want it to. ok thanks

**Comment by ArjixWasTaken** [comment]
As you can see from my log

```
17:30:19 [INFO] osu! path: "C:\\Users\\Arjix\\AppData\\Local\\osu!/osu!.exe"
17:30:19 [INFO] Got a link! https://osu.ppy.sh/beatmaps/yyyyy
17:30:19 [INFO] Got redirected!! https://osu.ppy.sh/beatmapsets/xxxxx#osu/yyyyy
17:30:19 [INFO]     Attempting to download from chimu.moe - https://api.chimu.moe/v1/download/xxxxx
17:30:21 [INFO]     Successfully downloaded beatmap from chimu.moe!
17:30:21 [INFO] Saved the beatmap to: "C:\\Users\\Arjix\\AppData\\Local\\osu!directer-beatmaps\\xxxxx_chimu.osz"
17:30:21 [INFO] Launching osu! at "C:\\Users\\Arjix\\AppData\\Local\\osu!/osu!.exe"
```

The link that osu tries to open in your browser, is `https://osu.ppy.sh/beatmaps/yyyyy`, there is no way for my code to know when you are trying to open a beatmap in the browser and when you are trying to download a beatmap.

Although, now that I think about it, I could scan all the osu beatmaps and see if the beatmap is already downloaded, if it is already downloaded then it should open the browser.
